name: go
version: 0.0.1
description: An absolute bare-bones web app.

environment:
  sdk: '>=1.0.0 <2.0.0'
  
dependencies:
  bootjack: any
  browser: any
  react: any
  w_flux:
    git: git://github.com/Workiva/w_flux
  w_module:
    git: git://github.com/Workiva/w_module
